<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CandidatesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('candidates')->insert([
            [
                'last_name' => 'Santos',
                'first_name' => 'Maria',
                'middle_name' => null,
                'suffix_name' => null,
                'ministry_involvement' => 'Worship Team',
                'age' => 18,
                'grade_year' => 'Grade 12',
                'course_strand' => 'ABM',
                'school' => 'Faith Academy',
                'church_id' => 1,
                'position_id' => 1,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Cruz',
                'first_name' => 'Juan',
                'middle_name' => 'Reyes',
                'suffix_name' => null,
                'ministry_involvement' => 'Youth Ministry',
                'age' => 20,
                'grade_year' => '2nd Year College',
                'course_strand' => 'BSIT',
                'school' => 'City College',
                'church_id' => 1,
                'position_id' => 2,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Dela Cruz',
                'first_name' => 'Ana',
                'middle_name' => 'Lopez',
                'suffix_name' => null,
                'ministry_involvement' => 'Children’s Ministry',
                'age' => 19,
                'grade_year' => '1st Year College',
                'course_strand' => 'BSEd',
                'school' => 'State University',
                'church_id' => 1,
                'position_id' => 3,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Garcia',
                'first_name' => 'Mark',
                'middle_name' => 'Antonio',
                'suffix_name' => 'Jr.',
                'ministry_involvement' => 'Ushering Ministry',
                'age' => 21,
                'grade_year' => '3rd Year College',
                'course_strand' => 'BSBA',
                'school' => 'Faith University',
                'church_id' => 1,
                'position_id' => 1,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Lopez',
                'first_name' => 'Ella',
                'middle_name' => 'Mae',
                'suffix_name' => null,
                'ministry_involvement' => 'Media Team',
                'age' => 17,
                'grade_year' => 'Grade 11',
                'course_strand' => 'STEM',
                'school' => 'Hope Academy',
                'church_id' => 1,
                'position_id' => 4,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Villanueva',
                'first_name' => 'John',
                'middle_name' => 'Paul',
                'suffix_name' => null,
                'ministry_involvement' => 'Music Ministry',
                'age' => 22,
                'grade_year' => 'Graduate',
                'course_strand' => 'BSCE',
                'school' => 'City University',
                'church_id' => 1,
                'position_id' => 2,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Reyes',
                'first_name' => 'Karla',
                'middle_name' => 'Ann',
                'suffix_name' => null,
                'ministry_involvement' => 'Prayer Ministry',
                'age' => 18,
                'grade_year' => 'Grade 12',
                'course_strand' => 'HUMSS',
                'school' => 'Grace Academy',
                'church_id' => 1,
                'position_id' => 5,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Torres',
                'first_name' => 'Miguel',
                'middle_name' => 'Luis',
                'suffix_name' => null,
                'ministry_involvement' => 'Tech Team',
                'age' => 19,
                'grade_year' => '1st Year College',
                'course_strand' => 'BSCS',
                'school' => 'Hope University',
                'church_id' => 1,
                'position_id' => 3,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Bautista',
                'first_name' => 'Sophia',
                'middle_name' => 'Marie',
                'suffix_name' => null,
                'ministry_involvement' => 'Dance Ministry',
                'age' => 17,
                'grade_year' => 'Grade 11',
                'course_strand' => 'GAS',
                'school' => 'Trinity School',
                'church_id' => 1,
                'position_id' => 4,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Fernandez',
                'first_name' => 'Liam',
                'middle_name' => 'Kyle',
                'suffix_name' => null,
                'ministry_involvement' => 'Outreach Ministry',
                'age' => 20,
                'grade_year' => '2nd Year College',
                'course_strand' => 'BSN',
                'school' => 'Central College',
                'church_id' => 1,
                'position_id' => 5,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_name' => 'Mendoza',
                'first_name' => 'Isabella',
                'middle_name' => 'Rose',
                'suffix_name' => null,
                'ministry_involvement' => 'Choir',
                'age' => 18,
                'grade_year' => 'Grade 12',
                'course_strand' => 'ABM',
                'school' => 'Blessed Hope Academy',
                'church_id' => 1,
                'position_id' => 1,
                'photo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
