name: Deploy Laravel Backend to Railway

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'resources/js/**'  # Ignore frontend changes

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, intl, bcmath
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PROJECT_ID: ${{ secrets.BACKEND_PROJECT_ID }}
        run: railway up --service ncmd-backend
